window.STUDY_CONFIG = {
  STUDY_TITLE: "Moral Intuition Study",
  GAS_ENDPOINT: "PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE",
  PROLIFIC_COMPLETION_URL: "https://app.prolific.com/submissions/complete?cc=PASTE_YOUR_COMPLETION_CODE",
  REDIRECT_DELAY_MS: 900,
  ALLOW_PREVIEW_WITHOUT_PROLIFIC: true
};

